kind: ConfigMap
apiVersion: v1
metadata:
  name: devspaces-user-configmap
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /projects/home/.continue
data:
  config.yaml: |
    name: code-assistant-config
    version: 0.0.1
    schema: v1
    models:
      - name: Granite 3.3 2b Local
        model: granite3.3:2b
        defaultCompletionOptions:
          contextLength: 128000
        provider: openai
        apiBase: https://llama-cpp-code-assistant-01-code-assistant.apps.nuc-15.clg.lab/v1
        apiKey: NA
        requestOptions:
          caBundlePath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          timeout: 300000
        roles:
          - chat
          - edit
          - autocomplete
          - apply
        capabilities:
          - tool_use
      - name: Qwen 3 1.7b Local
        model: qwen3:1.7b
        defaultCompletionOptions:
          contextLength: 40960
        provider: openai
        apiBase: https://llama-cpp-code-assistant-02-code-assistant.apps.nuc-15.clg.lab/v1
        apiKey: NA
        requestOptions:
          caBundlePath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          timeout: 300000
        roles:
          - chat
          - edit
          - autocomplete
          - apply
        capabilities:
          - tool_use
      - name: Qwen 3 4b Local
        model: qwen3:4b
        defaultCompletionOptions:
          contextLength: 40960
        provider: llama.cpp
        apiBase: https://llama-cpp-code-assistant-03-code-assistant.apps.nuc-15.clg.lab
        apiKey: NA
        requestOptions:
          caBundlePath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          timeout: 300000
        roles:
          - chat
        capabilities:
          - tool_use
      - name: CLG-LAB-DS1
        model: deepseek-r1-distill-qwen-14b
        provider: openai
        apiBase: https://deepseek-r1-distill-qwen-14b-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com/v1
        apiKey: YOUR_KEY_HERE
        defaultCompletionOptions:
          contextLength: 50000
        roles:
          - chat
          - edit
          - autocomplete
          - apply
        capabilities:
          - tool_use
      - name: Granite Embeddings
        model: granite-embedding-278m-multilingual
        provider: openai
        apiBase: https://granite-embedding-278m-multilingual-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1
        apiKey: YOUR_KEY_HERE
        roles:
          - embed
    docs:
      - name: Quarkus Guides
        faviconUrl: ""
        startUrl: https://quarkus.io/guides
