kind: Namespace
apiVersion: v1
metadata:
  name: code-assistant
---
kind: Service
apiVersion: v1
metadata:
  name: llama-cpp-code-assistant-01
  namespace: code-assistant
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: llama-cpp-code-assistant-01
---
kind: Service
apiVersion: v1
metadata:
  name: llama-cpp-code-assistant-02
  namespace: code-assistant
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: llama-cpp-code-assistant-02
---
kind: Service
apiVersion: v1
metadata:
  name: llama-cpp-code-assistant-03
  namespace: code-assistant
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: llama-cpp-code-assistant-03
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: llama-cpp-code-assistant-01
  namespace: code-assistant
spec:
  to:
    kind: Service
    name: llama-cpp-code-assistant-01
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: llama-cpp-code-assistant-02
  namespace: code-assistant
spec:
  to:
    kind: Service
    name: llama-cpp-code-assistant-02
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: llama-cpp-code-assistant-03
  namespace: code-assistant
spec:
  to:
    kind: Service
    name: llama-cpp-code-assistant-03
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-code-assistant-01
  namespace: code-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-code-assistant-02
  namespace: code-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-code-assistant-03
  namespace: code-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-code-assistant-01
  namespace: code-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp-code-assistant-01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: llama-cpp-code-assistant-01
      annotations:
        io.kubernetes.cri-o.Devices: "/dev/dri/renderD128"
    spec:
      containers:
      - name: llama-cpp-code-assistant-01
        # image: quay.io/cgruver0/che/my-code-assistant:latest
        image: nexus.clg.lab:5002/dev-spaces/my-code-assistant:latest
        imagePullPolicy: Always
        env:
        - name: MODEL
          value: granite3.3:2b
        - name: RAMALAMA_STORE
          value: /ramalama
        - name: LLAMA_CPP_CTX
          value: "128000"
        - name: LLAMA_CPP_GPU
          value: SYCL0
        args:
          - 'llama-server'
          - '--jinja'
          - '--model'
          - $(RAMALAMA_STORE)/models/ollama/$(MODEL)
          - '--host'
          - 0.0.0.0
          - '--n-gpu-layers'
          - '999'
          - '--flash-attn'
          - '--ctx-size'
          - $(LLAMA_CPP_CTX)
          - '--device'
          - $(LLAMA_CPP_GPU)
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: '8'
            memory: 32Gi
          requests:
            cpu: '100m'
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 8
          periodSeconds: 100
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 600
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ramalama
          name: llama-cpp-code-assistant-01
      restartPolicy: Always
      volumes:
      - name: llama-cpp-code-assistant-01
        persistentVolumeClaim:
          claimName: llama-cpp-code-assistant-01
      nodeSelector:
        node-role.kubernetes.io/gpu: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llama-cpp-code-assistant-02
                - llama-cpp-code-assistant-03
            topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-code-assistant-02
  namespace: code-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp-code-assistant-02
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: llama-cpp-code-assistant-02
      annotations:
        io.kubernetes.cri-o.Devices: "/dev/dri/renderD128"
    spec:
      containers:
      - name: llama-cpp-code-assistant-02
        # image: quay.io/cgruver0/che/my-code-assistant:latest
        image: nexus.clg.lab:5002/dev-spaces/my-code-assistant:latest
        imagePullPolicy: Always
        env:
        - name: MODEL
          value: granite3.3:2b
        - name: RAMALAMA_STORE
          value: /ramalama
        - name: LLAMA_CPP_CTX
          value: "128000"
        - name: LLAMA_CPP_GPU
          value: SYCL0
        args:
          - 'llama-server'
          - '--jinja'
          - '--model'
          - $(RAMALAMA_STORE)/models/ollama/$(MODEL)
          - '--host'
          - 0.0.0.0
          - '--n-gpu-layers'
          - '999'
          - '--flash-attn'
          - '--ctx-size'
          - $(LLAMA_CPP_CTX)
          - '--device'
          - $(LLAMA_CPP_GPU)
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: '8'
            memory: 32Gi
          requests:
            cpu: '100m'
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 8
          periodSeconds: 100
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 600
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ramalama
          name: llama-cpp-code-assistant-02
      restartPolicy: Always
      volumes:
      - name: llama-cpp-code-assistant-02
        persistentVolumeClaim:
          claimName: llama-cpp-code-assistant-02
      nodeSelector:
        node-role.kubernetes.io/gpu: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llama-cpp-code-assistant-01
                - llama-cpp-code-assistant-03
            topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-code-assistant-03
  namespace: code-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp-code-assistant-03
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: llama-cpp-code-assistant-03
      annotations:
        io.kubernetes.cri-o.Devices: "/dev/dri/renderD128"
    spec:
      containers:
      - name: llama-cpp-code-assistant-03
        # image: quay.io/cgruver0/che/my-code-assistant:latest
        image: nexus.clg.lab:5002/dev-spaces/my-code-assistant:latest
        imagePullPolicy: Always
        env:
        - name: MODEL
          value: granite3.3:2b
        - name: RAMALAMA_STORE
          value: /ramalama
        - name: LLAMA_CPP_CTX
          value: "128000"
        - name: LLAMA_CPP_GPU
          value: SYCL0
        args:
          - 'llama-server'
          - '--jinja'
          - '--model'
          - $(RAMALAMA_STORE)/models/ollama/$(MODEL)
          - '--host'
          - 0.0.0.0
          - '--n-gpu-layers'
          - '999'
          - '--flash-attn'
          - '--ctx-size'
          - $(LLAMA_CPP_CTX)
          - '--device'
          - $(LLAMA_CPP_GPU)
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: '8'
            memory: 32Gi
          requests:
            cpu: '100m'
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          timeoutSeconds: 8
          periodSeconds: 100
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 600
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ramalama
          name: llama-cpp-code-assistant-03
      restartPolicy: Always
      volumes:
      - name: llama-cpp-code-assistant-03
        persistentVolumeClaim:
          claimName: llama-cpp-code-assistant-03
      nodeSelector:
        node-role.kubernetes.io/gpu: ""
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llama-cpp-code-assistant-02
                - llama-cpp-code-assistant-01
            topologyKey: kubernetes.io/hostname